services:
  monbooru:
    container_name: monbooru

    # you can use monbooru:latest-cuda if you have a CUDA compatible GPU, or
    # monbooru:latest-openvino for an Intel GPU, for faster auto-tagging
    image: ghcr.io/monbooru/monbooru:latest

    # if using CUDA, pass the GPU to the container
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

    # if using OpenVINO: 
    #devices:
    #  - /dev/dri:/dev/dri
    #group_add:
    #  - "993"

    ## set it to your host uid:gid
    user: "1000:1000"

    ports:
      - "127.0.0.1:8455:8455"
    security_opt:
      - no-new-privileges:true

    ## Drop all capabilities. CHOWN + DAC_OVERRIDE are only needed if your
    ## gallery files are owned by a different uid than the container runs as.
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE

    volumes:
      - /path/to/your/models:/models:ro
      - /path/to/your/gallery:/gallery
      # Additional galleries (need to be mounted in settings)
      # - /path/to/your/gallery2:/gallery2
      # - /path/to/your/gallery3:/gallery3
      - /path/to/monbooru/config:/config
      - /path/to/monbooru/data:/data
    environment:
      - MONBOORU_SERVER_BIND_ADDRESS=0.0.0.0:8455
      # Base URL (The one you use to reach monbooru from the browser)
      - MONBOORU_SERVER_BASE_URL=http://localhost:8455
      # - TZ=Etc/UTC
    restart: unless-stopped

  ## monloader is an optional online boorus and galleries downloader.
  ## it allows you to download images and their tags directly into monbooru.
  ## see https://github.com/monbooru/monloader for more details.
  monloader:
    image: ghcr.io/monbooru/monloader:latest
    container_name: monloader
    user: "1000:1000"
    ports:
      - "127.0.0.1:8456:8456"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - /path/to/monloader/config:/config
      # If you want to enable the Public Tag Repository syncing (>70GB required)
      # - /path/to/monloader/ptr:/ptr
    environment:
      - MONLOADER_SERVER_BIND_ADDRESS=0.0.0.0:8456
      - MONLOADER_SERVER_BASE_URL=http://localhost:8456
    depends_on:
      - monbooru
    restart: unless-stopped
